#!/usr/bin/env python3

import argparse
from pygitsh import *

parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='create a new repository'
        )


parser.add_argument('-d', '--description', help='set description of the repository', default='my awesome repository')
parser.add_argument('-o', '--owner', help='set owner of the repository', default='git')
parser.add_argument('-P', '--private', action='store_true', help='make this repository private, i.e. do not show at gitweb access')
parser.add_argument('-U', '--uri', help='clone from URI instead of initialize an empty repository')
parser.add_argument('name', help='repository name', metavar='NAME')
args = parser.parse_args()

if repo_exists(args.name):
    logger.error('repository %s exists' % args.name)
    exit(1)

if '.' in args.name.rstrip('.git'):
    logger.warning('including "." in NAME may cause problems')

if not args.uri:
    create_repo(args.name)
else:
    create_repo_from_uri(args.name, args.uri)
set_repo_description(args.name, args.description)
set_repo_owner(args.name, args.owner)

if not args.private:
    set_repo_private(args.name, False)
