#!/usr/bin/env python3

import argparse
from glob import glob
from pygitsh import *

parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='list repositories'
        )

scope_group = parser.add_mutually_exclusive_group()
scope_group.add_argument('-a', '--all', action='store_true', help='show all repositories')
scope_group.add_argument('-b', '--backups', action='store_true', help='show only backups')

args = parser.parse_args()

if not args.backups:
    print("Repositories:")
    print('%-15s%-15s%-40s%s' % ('Name', 'Owner', 'Description', 'Private'))
    for f in find_repos():
        print('%-15s%-15s%-40s%s' % (repo_name(f), repo_owner(f), repo_description(f), repo_private(f)))

if args.all:
    print()

if args.all or args.backups:
    print("Backups:")
    print('%-40s%s' % ('Name', 'Create Time'))
    for f in find_backups():
        name = repo_name(f)
        ctime = int(repo_name(f).rsplit('.', 1)[1])
        print('%-40s%s' % (name,  time.strftime('%FT%TZ', time.gmtime(ctime))))
