#!/bin/sh

enabled="$(git config --bool deploy.use || printf 'false')"
name="$(git config deploy.name)"
key="$(git config deploy.key)"

HOOK_URL="http://localhost:7500/hooks"

if [ "$enabled" = 'true' ]; then
    echo "calling deploy hook."
    echo "we do not guarantee this build to succeed."
    curl -s -d "key=$key" "${HOOK_URL}/$name"
else
    echo "no deploy needed."
fi
