#!/bin/sh

repo="$PWD"
workdir="$(mktemp -d -t deploy-XXXXX)"

git --work-tree="$workdir" checkout -f master
echo "starting deployment..."
echo "work at $workdir"
pushd "$workdir"
make deploy
rc="$?"
if test "$rc" -eq 0; then
    echo "succeed"
else
    echo "returns $rc"
fi
popd
rm -rf "$workdir"
